export const sentences = [
    'Click to get a boost from the motiv8-ball',
    'Better days are on their way',
    'Growth doesn’t always feel like growth',
    'Your effort will pay off — keep going',
    'Believe in the process',
    'Your effort matters',
    'Don’t give up now',
    'Your next opportunity is on its way',
    'Your effort today builds tomorrow',
    'Believe in yourself a little extra today',
    'You’ve overcome harder things before',
    'Stay focused — your future self thanks you',
    'One interview can change everything',
    'Someone out there needs your skills',
    'The right manager will notice you',
    'Believe in what you bring to the table',
    'Your next “yes” is getting closer',
    'Every project builds your next skill',
    'Your future team will be lucky to have you',
    'You deserve a great role',
    'You’re doing better than you realize',
    'Every effort moves you closer',
    'The right team is looking for you too',
    'You have more to offer than you realize',
    'Better days are forming behind the scenes',
    'Slow progress is still progress',
    'Take a snack break. Doctor’s orders.',
    'One door closes, a better one opens',
    'You got this. Seriously.',
    'Today is a great day to network',
    'Small wins lead to big features',
    'Every error teaches you something new',
    'Be kind to your past self',
    'Focus on what you can control',
    'Rest is part of the process',
    'You are enough, right now',
    'Take a deep breath and reset',
    'Stay curious',
    'Your perfect fit is coming soon',
    'It is just a feature, not a bug',
    'The answer is 42',
    'A tired mind writes bad code. Pause',
    'Time for a quick stretch',
    'Let’s commit to a great day',
    'Just do it!',
    'Stop comparing and start creating',
];
